Update tpn for mask
spacetelescope/crds pull request #838
Opened 2021-08-12 20:13 UTC by ddkauffman

2021-08-12 20:22 UTC, nden approved these changes

2021-08-13 11:14 UTC, nden requested changes
`reftypes_roman_reference_name_to_tpn_infos()` needs to be update to include the `ORIGIN` attribute

The Roman test data in crds-test need to be updated to the latest schemas

2021-08-24 21:15 UTC, nden commented
@ddkauffman Can this be closed?

2021-08-31 19:03 UTC, closed without merging

2021-08-31 19:04 UTC, ddkauffman commented
Changes already included in another branch