Add 'delivered' as an allowed state for crds sync
spacetelescope/crds pull request #903
Opened 2022-09-30 13:32 UTC by jdavies-st

Resolves #902

2022-10-19 07:04 UTC, jdavies-st commented
Tagging @alphasentaurii and @stscieisenhamer for review.  🚀

2022-10-20 14:19 UTC, alphasentaurii requested changes
Just need to rebase from master to resolve merge conflict

2022-10-20 15:27 UTC, jdavies-st commented
Should this PR get milestoned into today's release for the CHANGE log?  Or into an unreleased section?

2022-10-20 18:16 UTC, alphasentaurii approved these changes

2022-10-24 12:36 UTC, stscieisenhamer approved these changes

2022-10-24 12:36 UTC, merged